OnlineLinkConverter/Controllers/GroupsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineLinkConverter.Data.Interfaces;
using OnlineLinkConverter.Data.Repository;
using OnlineLinkConverter.Data.ViewModels;
using OnlineLinkConverter.Data.ViewServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using static OnlineLinkConverter.Data.Enums.PageEnums;

namespace OnlineLinkConverter.Controllers
{
    [Authorize]
    public class GroupsController : Controller
    {
        private readonly RepositoryManager repositoryManager;
        private readonly ServicesManager serviceManager;
        private readonly UserManager<IdentityUser> userManager;


        public GroupsController(RepositoryManager repositoryManager, IHttpContextAccessor httpContextAccessor, UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
            this.repositoryManager = repositoryManager;
            serviceManager = new ServicesManager(repositoryManager, httpContextAccessor);
        }

        public async Task<IActionResult> Details(int pageId, PageType pageType)
        {
            PageViewModel pageViewModel;
            switch (pageType)
            {
                case PageType.Group: pageViewModel = await serviceManager.Groups.GroupDBToViewModelByIdAsync(pageId); break;
                case PageType.Link: pageViewModel = await serviceManager.Links.LinkDBModelToViewAsync(pageId); break;
                default: pageViewModel = null; break;
            }
            ViewBag.PageType = pageType;
            return View(pageViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> PageEditor(int pageId, PageType pageType, int groupId = 0)
        {            

            PageEditModel pageEditModel;
            switch (pageType)
            {
                case PageType.Group: 
                    if(pageId != 0)
                        pageEditModel = await serviceManager.Groups.GetGroupEditModelAsync(pageId); 
                    else
                        pageEditModel = await serviceManager.Groups.CreateNewGroupEditModelAsync();
                    break;
                case PageType.Link:
                    if (pageId != 0)
                        pageEditModel = await serviceManager.Links.GetLinkEditModelAsync(pageId);
                    else
                        pageEditModel = await serviceManager.Links.CreateNewLinkEditModelAsync(groupId);
                    break;
                default: pageEditModel = null; break;
            }
            ViewBag.PageType = pageType;
            return View(pageEditModel);
        }

        [HttpPost]
        public async Task<IActionResult> AddGroup(GroupEditModel model)
        {
            await serviceManager.Groups.SaveGroupEditModelToDBAsync(model);
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> AddLink(LinkEditModel model)
        {
            await serviceManager.Links.SaveLinkEditModelToDbAsync(model);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> RemoveGroup(int groupId)
        {
            await serviceManager.Groups.RemoveGroupFromDbAsync(groupId);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> RemoveLink(int linkId)
        {
            await serviceManager.Links.RemoveLinkFromDbAsync(linkId);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> AllLinks()
        {
            var user = await userManager.GetUserAsync(User);
            List<GroupViewModel> groups = await serviceManager.Groups.GetGroupListAsync(user.Id);
            return View(groups);
        }

        public async Task<IActionResult> OLCRedirect(string groupId, string linkId)
        {
            int intLinkId = Convert.ToInt32(linkId, 16);
            LinkViewModel model = await serviceManager.Links.LinkDBModelToViewAsync(intLinkId);
            //string page = "https://localhost:44362/";
            string page = "https://onlinelinkconverter.azurewebsites.net/";
            if (model.Link.IsActive)
            {
                page = model.Link.BaseLink;
            }
            return Redirect(page);
        }
    }
}

OnlineLinkConverter/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using OnlineLinkConverter.Data.Repository;
using OnlineLinkConverter.Data.ViewModels;
using OnlineLinkConverter.Data.ViewServices;
using OnlineLinkConverter.Models;

namespace OnlineLinkConverter.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private readonly RepositoryManager repositoryManager;
        private readonly ServicesManager serviceManager;
        private readonly UserManager<IdentityUser> userManager;

        public HomeController(RepositoryManager repositoryManager, IHttpContextAccessor httpContextAccessor, UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
            this.repositoryManager = repositoryManager;
            serviceManager = new ServicesManager(repositoryManager, httpContextAccessor);
        }

        public async Task<IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);
            List<GroupViewModel> groups = await serviceManager.Groups.GetGroupListAsync(user.Id);
            return View(groups);
        }
                    

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OnlineLinkConverter/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

OnlineLinkConverter/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineLinkConverter/Views/Home/Index.cshtml
@using OnlineLinkConverter.Data.ViewModels;
@using OnlineLinkConverter.Data.Enums;
@model List<GroupViewModel>

@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    .block {        
        background: #ccc;
        padding: 10px;
    }
</style>

<h2>Группы ссылок</h2>

<div class="row mt-5 mb-2">
    @{        
        foreach (var item in Model)
        {
            <p></p>
            <div class="block">
                <h4>@item.Group.Name</h4>
                <p>@item.Group.Description</p>
                <p>Количество ссылок: @item.Links.Count()</p>
                <p>
                    <a class="btn btn-warning" asp-action="Details" asp-controller="Groups" asp-route-pageId="@item.Group.Id" asp-route-pageType="@PageEnums.PageType.Group">Войти в группу</a>
                    <a class="btn btn-warning" asp-action="PageEditor" asp-controller="Groups" asp-route-pageId="@item.Group.Id" asp-route-pageType="@PageEnums.PageType.Group">Редактировать</a>
                </p>
            </div>
            <p></p>
        }
    }
</div>

<p></p>

<div>
    <p><a class="btn btn-warning" asp-action="PageEditor" asp-controller="Groups" asp-route-pageId="0" asp-route-pageType="@PageEnums.PageType.Group">Добавить группу</a></p>
</div>